### Expect 'pong' (status code 200)
GET http://localhost:5000/ping

### Expect an array with all the users (status code 200)
GET http://localhost:5000/users

### Expect sucessful user creation (status code 201)
POST http://localhost:5000/users HTTP/1.1
Content-Type: application/json

{
  "name": "Nath"
}
